version: '3.6'
services:
  discordbot:
    image: ocn-killbot:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
    volumes:
      - ./config:/workspace/dist/config:delegated

networks:
  default:
    name: bot-network
    driver: bridge
